### ISSUE TITLE
Network access gitlab

### ISSUE THREAD

**Issue by sinteur** [radicallyopensecurity/infra#1]
I've got gitlab set up and running on 94.143.212.55, a new VM.

I've set up ssh on it, and configured it on the firewall and NAT and that works (port 7722 to 22)

I've also set up gitlab and it's listening on 8088, but the firewall and NAT does NOT work despite being set up identical to the ssh.

I'm obviously missing something simple - could anybody have a look for me?

**Comment by giray** [comment]
sorry ... didn't get around to it yesterday ... looking now
